#!/usr/bin/env python3
"""Mechanical side of an ADR archive (MADR minimal). Standard library only.

Usage:
    adr.py audit  DIR                                  # check the archive, exit 1 on errors
    adr.py index  DIR                                  # regenerate DIR/index.md from front-matter
    adr.py new    DIR "Title" [--status proposed|accepted]
                              [--supersedes NNNN] [--description "..."]
    adr.py status DIR NNNN <status> [--by NNNN]        # validated status transition

Everything language-specific (section names, front-matter keys) is derived from the
archive's own template.md, so the same script serves an English or a pt-BR archive.
Without a template.md the English defaults apply.
"""

import re
import sys
import unicodedata
from datetime import date
from pathlib import Path

STATUSES = ["proposed", "accepted", "rejected", "superseded", "deprecated"]
TRANSITIONS = {
    "proposed": {"accepted", "rejected"},
    "accepted": {"superseded", "deprecated"},
    "rejected": set(),
    "superseded": set(),
    "deprecated": set(),
}
FILENAME_RE = re.compile(r"^(\d{4})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
H1_RE = re.compile(r"^#\s+(\d{4})\.\s+(\S.*)$", re.MULTILINE)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
ANY_DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
URL_RE = re.compile(r"https?://\S+")
FM_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
SKIP = {"readme.md", "template.md", "index.md"}

DEFAULT_SECTIONS = ["## Context and problem", "## Considered options", "## Decision", "## Consequences", "## References"]
DEFAULT_FM_KEYS = ["status", "date", "title", "description", "supersedes", "superseded-by"]
# The last section of the template is optional (References): checked only when present.
INDEX_MARKER = "<!-- Generated by adr.py index. Do not edit by hand. -->"

errors, warnings = [], []


def err(f, msg):
    errors.append((f, msg))


def warn(f, msg):
    warnings.append((f, msg))


# ---------------------------------------------------------------- parsing

def parse_front_matter(text):
    """Flat `key: value` front-matter. None when missing or malformed."""
    m = FM_RE.match(text)
    if not m:
        return None
    data = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            return None
        k, v = line.split(":", 1)
        data[k.strip()] = v.strip().strip("\"'")
    return data


def set_front_matter(text, updates):
    """Rewrite the given keys in place, keeping every other line untouched."""
    m = FM_RE.match(text)
    lines = m.group(1).splitlines()
    out = []
    for line in lines:
        key = line.split(":", 1)[0].strip() if ":" in line else None
        if key in updates:
            out.append(f"{key}: {updates[key]}".rstrip())
        else:
            out.append(line)
    return text[: m.start(1)] + "\n".join(out) + text[m.end(1):]


def archive_schema(adr_dir):
    """Required sections and front-matter keys, read from the archive's template.md."""
    tpl = adr_dir / "template.md"
    if not tpl.is_file():
        return DEFAULT_SECTIONS, DEFAULT_FM_KEYS
    text = tpl.read_text(encoding="utf-8")
    sections = [s.strip() for s in re.findall(r"^##\s+.+$", text, re.MULTILINE)]
    fm = parse_front_matter(text)
    return (sections or DEFAULT_SECTIONS), (list(fm.keys()) if fm else DEFAULT_FM_KEYS)


def section_body(text, heading, all_headings):
    start = text.find(heading)
    if start < 0:
        return ""
    start += len(heading)
    ends = [text.find(h, start) for h in all_headings if text.find(h, start) > -1]
    return text[start: min(ends)] if ends else text[start:]


def load_archive(adr_dir):
    """Every NNNN-*.md as {number: {name, fm, status, text, h1_title}}; files with a bad
    name or front-matter are reported and skipped."""
    files = sorted(p for p in adr_dir.glob("*.md") if p.name.lower() not in SKIP)
    adrs, by_number = {}, {}
    for path in files:
        name = path.name
        m = FILENAME_RE.match(name)
        if not m:
            err(name, "file name is not NNNN-kebab-case-title.md")
            continue
        text = path.read_text(encoding="utf-8")
        fm = parse_front_matter(text)
        if fm is None:
            err(name, "front-matter missing or malformed (a --- ... --- block at the top)")
            continue
        number = m.group(1)
        h1 = H1_RE.search(text)
        by_number.setdefault(number, []).append(name)
        adrs[number] = {
            "name": name, "path": path, "fm": fm, "status": fm.get("status", ""),
            "text": text, "h1": h1,
        }
    for number, names in sorted(by_number.items()):
        if len(names) > 1:
            err(", ".join(names), f"number {number} is used twice; numbers are never reused")
    return files, adrs


# ---------------------------------------------------------------- index

def render_index(adrs):
    lines = ["# Architecture Decision Records", "", INDEX_MARKER, "", "| # | decision | status | date |", "|---|---|---|---|"]
    for number, adr in sorted(adrs.items()):
        fm = adr["fm"]
        title = fm.get("title") or (adr["h1"].group(2).strip() if adr["h1"] else "(untitled)")
        lines.append(f"| [{number}]({adr['name']}) | {title} | {fm.get('status', '')} | {fm.get('date', '')} |")
    return "\n".join(lines) + "\n"


def write_index(adr_dir, adrs):
    path = adr_dir / "index.md"
    expected = render_index(adrs)
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current != expected:
        path.write_text(expected, encoding="utf-8")
        print(f"index.md regenerated ({path})")
    else:
        print("index.md already up to date")


# ---------------------------------------------------------------- audit

def audit(adr_dir):
    sections, fm_keys = archive_schema(adr_dir)
    optional = {sections[-1]} if len(sections) > 1 else set()
    files, adrs = load_archive(adr_dir)
    if not files:
        print(f"No ADRs in {adr_dir}.")
        return 0

    for number, adr in sorted(adrs.items()):
        name, fm, text, status = adr["name"], adr["fm"], adr["text"], adr["status"]
        for key in fm_keys:
            if key not in fm:
                err(name, f"front-matter lacks `{key}` (keep the key even when empty)")
        if status not in STATUSES:
            err(name, f"status `{status}` is not one of: {', '.join(STATUSES)}")
        d = fm.get("date", "")
        if not DATE_RE.match(d):
            err(name, f"date `{d}` is not ISO YYYY-MM-DD")
        if not adr["h1"]:
            err(name, "no `# NNNN. Title` heading in the body")
        elif adr["h1"].group(1) != number:
            err(name, f"heading number `{adr['h1'].group(1)}` differs from the file number `{number}`")
        for s in sections:
            if s not in optional and s not in text:
                err(name, f"required section missing: `{s}`")

        # Reading budget: a warning, not an error. Sections are located by name.
        ctx, opt, con = sections[0], sections[1], sections[3] if len(sections) > 3 else sections[-1]
        n_sent = len([s for s in re.split(r"[.!?]\s", section_body(text, ctx, sections).strip()) if s.strip()])
        if n_sent > 5:
            warn(name, f"{ctx[3:]} has ~{n_sent} sentences (budget 5); two decisions mixed together?")
        for heading, limit in ((opt, 4), (con, 5)):
            n = len(re.findall(r"^\s*[-*]\s+\S", section_body(text, heading, sections), re.MULTILINE))
            if n > limit:
                warn(name, f"{heading[3:]} has {n} bullets (budget {limit})")

        # References: optional, but usable when present.
        if optional and sections[-1] in text:
            refs = section_body(text, sections[-1], sections)
            bullets = re.findall(r"^\s*[-*]\s+\S.*$", refs, re.MULTILINE)
            if not bullets:
                err(name, f"`{sections[-1]}` has no source; cite one or remove the section")
            for b in bullets:
                if not URL_RE.search(b):
                    err(name, f"reference without a URL: {b.strip()[:60]}")
            if not ANY_DATE_RE.search(refs):
                warn(name, f"`{sections[-1]}` has no access date (YYYY-MM-DD); external facts age")

    # Supersede chains: both sides or neither.
    for number, adr in sorted(adrs.items()):
        name, fm, status = adr["name"], adr["fm"], adr["status"]
        by, sups = fm.get("superseded-by", ""), fm.get("supersedes", "")
        if status == "superseded" and not by:
            err(name, "status `superseded` without `superseded-by`; the chain dead-ends")
        if by and status != "superseded":
            err(name, f"has `superseded-by: {by}` but status is `{status}`, expected `superseded`")
        if by:
            t = adrs.get(by)
            if not t:
                err(name, f"`superseded-by: {by}` points to an ADR that does not exist")
            elif t["fm"].get("supersedes", "") != number:
                err(name, f"one-sided chain: {by} does not declare `supersedes: \"{number}\"`")
        if sups:
            t = adrs.get(sups)
            if not t:
                err(name, f"`supersedes: {sups}` points to an ADR that does not exist")
            else:
                if t["fm"].get("superseded-by", "") != number:
                    err(name, f"one-sided chain: {sups} does not declare `superseded-by: \"{number}\"`")
                if t["status"] != "superseded":
                    err(name, f"supersedes {sups}, but {sups} is `{t['status']}`")

    numbers = sorted(int(n) for n in adrs)
    missing = sorted(set(range(1, numbers[-1] + 1)) - set(numbers)) if numbers else []
    if missing:
        warn("-", "gaps in numbering: " + ", ".join(f"{n:04d}" for n in missing) + " (fine if they were deleted)")

    index = adr_dir / "index.md"
    if not index.is_file():
        warn("index.md", "missing; run `adr.py index DIR`")
    elif index.read_text(encoding="utf-8") != render_index(adrs):
        warn("index.md", "out of date; run `adr.py index DIR`")

    print(f"{len(files)} ADR(s) in {adr_dir}\n")
    for label, items in (("ERRORS", errors), ("WARNINGS", warnings)):
        if items:
            print(f"{label} ({len(items)}):")
            for f, msg in items:
                print(f"  {f}: {msg}")
            print()
    if not errors and not warnings:
        print("All consistent.")
    return 1 if errors else 0


# ---------------------------------------------------------------- new / status

def slugify(title):
    s = unicodedata.normalize("NFKD", title).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s or "untitled"


def flag(args, name):
    if name in args:
        i = args.index(name)
        if i + 1 >= len(args):
            raise SystemExit(f"error: {name} needs a value")
        value = args[i + 1]
        del args[i: i + 2]
        return value
    return None


def transition(adr, new_status, by, today):
    """Validate and apply one status change on a loaded ADR. Returns the new text."""
    old = adr["status"]
    if new_status not in STATUSES:
        raise SystemExit(f"error: `{new_status}` is not one of: {', '.join(STATUSES)}")
    if new_status not in TRANSITIONS.get(old, set()):
        allowed = ", ".join(sorted(TRANSITIONS.get(old, set()))) or "nothing (terminal)"
        raise SystemExit(f"error: {adr['name']} is `{old}`; it can only move to: {allowed}. "
                         "A rejected or superseded decision that comes back is a new ADR.")
    updates = {"status": new_status, "date": today}
    if new_status == "superseded":
        if not by:
            raise SystemExit("error: `superseded` needs --by NNNN")
        updates["superseded-by"] = f'"{by}"'
    return set_front_matter(adr["text"], updates)


def cmd_new(adr_dir, args):
    status = flag(args, "--status") or "proposed"
    supersedes = flag(args, "--supersedes")
    description = flag(args, "--description") or ""
    if len(args) != 1:
        raise SystemExit('usage: adr.py new DIR "Title" [--status s] [--supersedes NNNN] [--description "..."]')
    title = args[0].strip()
    if status not in ("proposed", "accepted"):
        raise SystemExit("error: a new ADR starts as `proposed` or `accepted`")
    tpl = adr_dir / "template.md"
    if not tpl.is_file():
        raise SystemExit(f"error: {tpl} not found; bootstrap the archive first")
    _, adrs = load_archive(adr_dir)
    if errors:
        for f, msg in errors:
            print(f"  {f}: {msg}")
        raise SystemExit("error: fix the archive before adding to it (see above)")
    today = date.today().isoformat()
    number = f"{(max((int(n) for n in adrs), default=0) + 1):04d}"
    path = adr_dir / f"{number}-{slugify(title)}.md"

    old_text = None
    if supersedes:
        old = adrs.get(supersedes)
        if not old:
            raise SystemExit(f"error: --supersedes {supersedes}: no such ADR")
        old_text = transition(old, "superseded", number, today)

    text = tpl.read_text(encoding="utf-8")
    text = set_front_matter(text, {
        "status": status, "date": today, "title": f'"{title}"',
        "description": f'"{description}"' if description else "",
        "supersedes": f'"{supersedes}"' if supersedes else "", "superseded-by": "",
    })
    text = re.sub(r"^#\s+NNNN\.\s+.*$", f"# {number}. {title}", text, count=1, flags=re.MULTILINE)
    text = text.replace("YYYY-MM-DD", today)
    path.write_text(text, encoding="utf-8")
    if old_text is not None:
        old["path"].write_text(old_text, encoding="utf-8")
        print(f"{old['name']}: status superseded, superseded-by {number}")
    print(f"created {path} ({status}); fill in the body, then run `adr.py index {adr_dir}`")
    return 0


def cmd_status(adr_dir, args):
    by = flag(args, "--by")
    if len(args) != 2:
        raise SystemExit("usage: adr.py status DIR NNNN <status> [--by NNNN]")
    number, new_status = args
    _, adrs = load_archive(adr_dir)
    adr = adrs.get(number)
    if not adr:
        raise SystemExit(f"error: no ADR {number} in {adr_dir}")
    if by and by not in adrs:
        raise SystemExit(f"error: --by {by}: no such ADR")
    today = date.today().isoformat()
    adr["path"].write_text(transition(adr, new_status, by, today), encoding="utf-8")
    print(f"{adr['name']}: {adr['status']} -> {new_status} ({today})")
    if by and adrs[by]["fm"].get("supersedes", "") != number:
        print(f"note: {adrs[by]['name']} does not declare `supersedes: \"{number}\"`; set it so the chain has both sides")
    return 0


def main():
    args = sys.argv[1:]
    if len(args) < 2:
        print(__doc__.strip())
        return 2
    cmd, adr_dir, rest = args[0], Path(args[1]), args[2:]
    if not adr_dir.is_dir():
        print(f"error: {adr_dir} is not a directory")
        return 2
    if cmd == "audit":
        return audit(adr_dir)
    if cmd == "index":
        _, adrs = load_archive(adr_dir)
        write_index(adr_dir, adrs)
        return 1 if errors else 0
    if cmd == "new":
        return cmd_new(adr_dir, rest)
    if cmd == "status":
        return cmd_status(adr_dir, rest)
    print(__doc__.strip())
    return 2


if __name__ == "__main__":
    sys.exit(main())
